# Project: Neospeech
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = Neospeech_private.res
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  -mwindows -s 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = Neospeech.exe
CXXFLAGS = $(CXXINCS)   -finput-charset=GBK -mwindows
CFLAGS = $(INCS)   -finput-charset=GBK -mwindows
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Neospeech.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Neospeech.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Neospeech_private.res: Neospeech_private.rc 
	$(WINDRES) -i Neospeech_private.rc --input-format=rc -o Neospeech_private.res -O coff 
